const Route = {
  INDEX: '/',
  ABOUT: '/about',
  USECASES: '/usecases',
  PRICING: '/pricing',
  BRAND: '/brand',
  TECHSTACK: '/techstack',
  SQL_REVIEW_GUIDE: '/sql-review-guide',
  BYTEBASE_PLUS: '/bytebase-plus',
  DATABASE_GLOSSARY: '/database-glossary',
  CHANGELOG: '/changelog',
  BLOG: '/blog',
  BLOG_CATEGORY: '/blog/category',
  DOCS: '/docs',
  DOCS_API: '/docs/api/overview',
  DOCS_CLI: '/docs/cli/overview',
  DOCS_HOW_TO: '/docs/how-to/sql-review/postgres-sql-review-guide',
  DOCS_TUTORIALS: '/docs/tutorials/overview',
  DATABASE_MYSQL: '/database/mysql',
  DATABASE_POSTGRES: '/database/postgres',
  DATABASE_TIDB: '/database/tidb',
  DATABASE_CLICKHOUSE: '/database/clickhouse',
  DATABASE_SNOWFLAKE: '/database/snowflake',
  INTEGRATION_GITLAB: '/integration/gitlab',
  INTEGRATION_GITHUB: '/integration/github',
  INTEGRATION_SLACK: '/integration/slack',
  INTEGRATION_DISCORD: '/integration/discord',
  INTEGRATION_TEAMS: '/integration/teams',
  INTEGRATION_DINGTALK: '/integration/dingtalk',
  INTEGRATION_LARK: '/integration/feishu',
  INTEGRATION_WECOM: '/integration/wecom',
  SOLUTIONS: '/solutions',
  USECASE_DBA: '/usecase/dba',
  USECASE_TECHLEAD: '/usecase/techlead',
  USECASE_DEVELOPER: '/usecase/developer',
  SELF_HOST: '/docs/get-started/install/deploy-with-docker',
  DISCORD: 'https://discord.com/invite/huyw7gRsyA',
  TWITTER: 'https://twitter.com/Bytebase',
  GITHUB: 'https://github.com/bytebase/bytebase',
  STAR_HISTORY: 'https://star-history.com/#bytebase/bytebase',
  DB_COST: 'https://www.dbcost.com/',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  JOBS: '/jobs',
};

export default Route;
