const Route = {
  INDEX: '/',
  ABOUT: '/about',
  USECASES: '/usecases',
  PRICING: '/pricing',
  SQL_REVIEW_GUIDE: '/sql-review-guide',
  BYTEBASE_PLUS: '/bytebase-plus',
  DATABASE_GLOSSARY: '/database-glossary',
  CHANGELOG: '/changelog',
  BLOG: '/blog',
  BLOG_CATEGORY: '/blog/category',
  DOCS: '/docs',
  DOCS_API: '/docs/api/overview',
  DOCS_CLI: '/docs/cli/overview',
  DOCS_HOW_TO: '/docs/how-to/sql-review/postgres-sql-review-guide',
  DOCS_TUTORIALS: '/docs/tutorials/overview',
  SOLUTIONS: '/solutions',
  DISCORD: 'https://discord.com/invite/huyw7gRsyA',
  TWITTER: 'https://twitter.com/Bytebase',
  GITHUB: 'https://github.com/bytebase/bytebase',
  TERMS: '/terms',
  PRIVACY: '/privacy',
};

export default Route;
